version: "3.2"

services:
  app-01:
    build: .
    command: nginx -t
    command: /app/api
    command: service nginx restart
    ports:
      - 5000:80
    networks:
      - seedx

  app-02:
    build: .
    command: nginx -t
    command: /app/api
    command: service nginx restart
    ports:
      - 5001:80
    networks:
      - seedx

networks:
  seedx:
    driver: bridge
