version: "3.2"

services:
  app-01:
    build: .
    container_name: app-01
    ports:
      - 5000:80
    networks:
      - seedx
  app-02:
    build: .
    container_name: app-02
    ports:
      - 5001:80
    networks:
      - seedx

networks:
  seedx:
    driver: bridge
