version: "3.2"

services:
  seedx-geen-ui:
    build: .
    tty: true
    command: bash -c "nginx -t && service nginx start && /app/api"
    ports:
      - "80:80"
    networks:
      - seedx

networks:
  seedx:
    driver: bridge
